name: Intune Configuration Backup

on:
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      include_beta_endpoints:
        description: 'Include beta Graph API endpoints'
        required: false
        type: boolean
        default: false

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  backup:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better diff support
          persist-credentials: true  # Keep credentials for push
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install all dependencies
        shell: cmd
        run: |
          build.cmd Install
      
      - name: Run all exports and generate change log
        shell: cmd
        run: |
          build.cmd ExportAll
      
      - name: Commit changes
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add exports/ change_logs/
          
          # Check if there are changes to commit
          $hasChanges = git diff --staged --quiet
          if ($LASTEXITCODE -eq 0) {
            Write-Host "No changes to commit"
          } else {
            $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC" -AsUTC
            git commit -m "Intune backup: $timestamp"
            git push
          }
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backup-logs
          path: |
            logs/
            change_logs/latest.json
